version: "3.7"
services:
  app:
    build:
      args:
        user: gabriel
        uid: 1000
      context: ./
      dockerfile: dockerfile
    image: chat-server
    container_name: chat-server-app
    restart: unless-stopped
    working_dir: /var/www/
    expose:
      - 9000
    volumes:
      - ./:/var/www
      - ./.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./.docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - chat-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
  db:
    image: postgres:11
    container_name: chat-db
    restart: unless-stopped
    ports:
      - 54320:5432
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./.docker/postgres:/docker-entrypoint-initdb.d
      - chat-dbdata:/var/lib/postgresql/data
    networks:
      - chat-network
  nginx:
    image: nginx:1.17-alpine
    container_name: chat-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d
    networks:
      - chat-network
  redis:
    image: redis:4.0
    container_name: chat-redis
    restart: unless-stopped
    ports:
      - 6382:6379
    volumes:
      - chat-redisdata:/data
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge
volumes:
  chat-dbdata:
  chat-redisdata: